.\" 
.\" man page for mudlet
.\"
.\" Copyright (C) 2011 Craig Small <csmall@debian.org>
.\"
.\" This man page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.pc
.TH MUDLET 1 2011-01-16
.SH NAME
mudlet \- Graphical Multi User Dungeon (MUD) client
.SH SYNOPSIS
.B mudlet
.SH DESCRIPTION
This manual page documents briefly the \fBmudlet\fR command. There are no
command line options. Just run the command  \fBmudlet\fR to start the GUI.
.SH OPTIONS
There are no options.
